[package]
name = "onscripter-web"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
actix-web = "4"
actix-files = "0.6"
clap = { version = "3", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
env_logger = "0.11.8"
